### ISSUE TITLE
constrains: column[0] >= column[1]

### ISSUE THREAD

**Issue by arsenius7** [adevress/syn2_spec#1]
Seems there is a typo at 'connected_neurons/neuron_to_range_pre' section.
`constrains: column[0] >= column[1]`
Shouldn't it be
`constrains: column[0] < column[1]`
?

**Comment by adevress** [comment]
that's right, thank you I will send a fix for that.

Don't hesitate to send a pull request if you have anything of this kind

**Comment by adevress** [comment]
Fixed with #4
