### ISSUE TITLE
small comments

### ISSUE THREAD

**Issue by jdcourcol** [adevress/syn2_spec#3]
picky comment: "x,y,z coordinates". may be define the referential. for instance, is it relative to the morphology center, is it relative to the atlas used to build the circuit.
"syn_type_recipe_id": are we forced to be linked to the recipe here?
"morphology specific id": what is that id ? how can I link it to the content of the MVD3 ?
"morpho_segment_post" and co: what do we do if the touche happen on a soma ?
"synapptic" : typo
"positions": you use plural for that one and not the others
"A population of synapses MUST BE independant of each other": can you elaborate ? do you mean that they cannot refer to the same morphologies ?

what would be the recommended way to add additional synapses (not found by functionalizer) due to projections for instance ?

**Comment by adevress** [comment]
Thx Jean-Denis.

Few comments :

"x,y,z coordinates" :  It follows the same coordinate system than the one on of the associated circuit MVD file. Meaning, absolute coordinated related to the atlas. I agree with you, that need to be precised in the spec.

"syn_type_recipe_id" and"morphology specific id". I don't like any of these parameter that can anyway be deduced from the build recipe. However I included them for forward compatibility with the existing tool if required. This need to be checked with Jim, and the In-sillicos users if we can drop them safetly or not.

"morpho_segment_post" : the soma is always identified as the branch "0" in every morphology format (h5v1, h5v2 )


"synapptic" : Thanks

"positions": Thanks 


"A population of synapses MUST BE independant of each other": My thought is that a population self-contain its own properties, index, and meta-data and do not share any data with other populations. They can be added and delete independently.

**Comment by adevress** [comment]
> what would be the recommended way to add additional synapses (not found by functionalizer) due to projections for instance ?

HDF5 supports the concept of "resizable dataset". It is possible to add additional synapses at the end of each dataset and regenerate the index.

Adding new synapse is a O(1) operation. However regenerating the index is not a cheap operation.

**Comment by adevress** [comment]
Fixed with #4
